# Generated by Django 4.2.5 on 2023-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_item',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
