# Generated by Django 4.2.5 on 2023-09-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_total_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_item',
        ),
    ]
